name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run ./postman/collections/MyCollection.postman_collection.json -e ./postman/environments/MyEnvironment.postman_environment.json --reporters cli,junit --reporter-junit-export ./postman-reports/junit-report.xml

    - name: Archive Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: postman-reports
        path: ./postman-reports/
