name: postman CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

     - uses: actions/checkout@v3
     - name: create dir
        run: |
              mkdir simpleartifact

    - name: install Node
      uses: actions/checkout@v3
      with:
        node-version: '17.x'

    - name: Install Newman and htmlextra
      run: |
        npm install -g newman
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run "postman/collections/CoingeckoCoin-idtestcases.postman_collection.json" -e "postman/environments/Development.postman_environment.json" -r htmlextra --reporter-htmlextra-export simpleartifact/report.html

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: simpleartifact
