name: postman CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      uses: actions/checkout@v3
      name: create dir
      run: |
            mkdir simpleartifact

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install Newman and htmlextra
      run: |
        npm install -g newman
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run "postman/collections/CoingeckoCoin-idtestcases.postman_collection.json" -e ./postman/environments/YourEnvironment.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export ./postman-reports/html-report.html

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: postman-report
        path: ./postman-reports/html-report.html
