name: postman CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create directory for report
      run: |
        mkdir -p simpleartifact

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install Newman and htmlextra
      run: |
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run "postman/collections/CoingeckoPriceAPITestcases.postman_collection.json" -e "postman/environments/Development.postman_environment.json" -r htmlextra --reporter-htmlextra-export simpleartifact/report.html

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: simpleartifact
